apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bytebot-llm-proxy.fullname" . }}
  labels:
    {{- include "bytebot-llm-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bytebot-llm-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bytebot-llm-proxy.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--config"
          - "/app/config.yaml"
          - "--port"
          - "{{ .Values.service.targetPort }}"
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- if .Values.env.ANTHROPIC_API_KEY }}
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "bytebot-llm-proxy.fullname" . }}-secrets
              key: anthropic-api-key
        {{- end }}
        {{- if .Values.env.OPENAI_API_KEY }}
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "bytebot-llm-proxy.fullname" . }}-secrets
              key: openai-api-key
        {{- end }}
        {{- if .Values.env.GEMINI_API_KEY }}
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "bytebot-llm-proxy.fullname" . }}-secrets
              key: gemini-api-key
        {{- end }}
        {{- if .Values.env.OPENROUTER_API_KEY }}
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "bytebot-llm-proxy.fullname" . }}-secrets
              key: openrouter-api-key
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: litellm-config.yaml
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: {{ include "bytebot-llm-proxy.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}